- src/R2Architecture.cpp
Basic arm16 / thumb support.
Note use "e r2ghidra.lang=ARM:LE:32:Cortex" for correct Thumb decompiling
> Basic arm16 / thumb support

- src/CodeXMLParse.cpp
This commit fixes a bug where do-while and if-else constructs
are not fully highlighted. Only the first opening keyword (i.e. `while`,
`if`) will be tagged by ghidra's XML as `<op>`. The secondary keywords
(i.e. `do` and `else`) are enclosed inside `<syntax>` tags.
To reproduce the bug/see the fix use the enclosed binary and check `s sym.rot13; pdg`.
[bin.zip](https://github.com/radareorg/r2ghidra-dec/files/3639865/bin.zip)
> Fix syntax highlighting of paired keywords

- src/core_ghidra.cpp
To make sure `code` isn't being null-referenced
> Reorder code

- src/R2Architecture.cpp
Since they are the same AFAIK.
Definition of `ms` in [radare2](https://github.com/radareorg/radare2/blob/5b392de33b84a4fd497cfda9d1af5b7b6333a963/libr/anal/d/cc-x86-64.sdb.txt#L3) and `__fastcall` in [ghidra](https://github.com/NationalSecurityAgency/ghidra/blob/decb362234d3ddfead76394b521e5669d2afac05/Ghidra/Processors/x86/data/languages/x86-64-win.cspec#L40), which should both representing [this](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019).
> Register "ms" CC in radare2 as "__fastcall" CC in ghidra

- src/R2Scope.cpp
This PR will make r2ghidra-dec honor realnames if asm.flags.real is set
**Before:**
```
...
uVar4 = (*_sym.imp.KERNEL32.dll_FindResourceW)(0, arg_8h_00 + 0x76U & 0xffff, 10);
uVar5 = (*_sym.imp.KERNEL32.dll_LoadResource)(0, uVar4);
uVar6 = (*_sym.imp.KERNEL32.dll_SizeofResource)(0, uVar4);
iVar7 = (*_sym.imp.KERNEL32.dll_LockResource)(uVar5);
...
```
**After:**
```
....
uVar4 = (*_FindResourceW)(0, arg_8h_00 + 0x76U & 0xffff, 10);
uVar5 = (*_LoadResource)(0, uVar4);
uVar6 = (*_SizeofResource)(0, uVar4);
iVar7 = (*_LockResource)(uVar5);
...
```
closes #68
> Honor asm.flags.real in output

- third-party/CMakeLists.txt
I want to package this for Fedora and distributions usually want to use as much as possible system libraries. As pugixml is available in Fedora, I want to be able to use that and this patch makes it possible by adding a new cmake option `USE_SYSTEM_PUGIXML`.
**Test plan**
Use `cmake -DUSE_SYSTEM_PUGIXML=ON ..` with pugixml-devel installed (or similar) and install the plugin. It should work as usual.
> Allow user to use system pugixml library

- src/CodeXMLParse.cpp
- test/db/extras/r2ghidra
Earlier we didn't have offset annotation (`R_CODE_ANNOTATION_TYPE_OFFSET`) for comments. Because of this, we have inconsistent behavior while clicking on a comment to edit in Cutter. This PR solves this problem by implementing offset annotations for comments.
The following GIFs show the previous behavior and improved behavior.
[Note: The following GIFs don't use the current master of Cutter. The same behavior can be noticed from the master also. So this PR can be merged after testing]
**Before having offset annotation**
**After implementing offset annotation**
...
**Test plan**
- Test with the current master of Cutter
- Test if the changes are working as expected
- Make sure nothing else is affected by this change
...
...
> Implemented offset annotation for comments

- scripts/Dockerfile.jessie
- src/CodeXMLParse.cpp
- test/db/extras/r2ghidra
This PR implements annotations for constant variables and global variables. The logic used to determine if a variable is global or constant is taken from the following [existing code](https://github.com/thestr4ng3r/ghidra/blob/6c10f36f06468f866188cccf960c019779fb9028/Ghidra/Features/Decompiler/src/decompile/cpp/variable.cc#L452-L470) in `variable.cc`. https://github.com/thestr4ng3r/ghidra/blob/6c10f36f06468f866188cccf960c019779fb9028/Ghidra/Features/Decompiler/src/decompile/cpp/variable.cc#L452-L470
As discussed in the Telegram channel, I'm making constant variable annotation only when address space is of name "ram". However, I couldn't find such a constant variable that satisfies this condition in the examples I have tried. I am not sure if such a constant …
> Annotation for constant and global variables

- src/CodeXMLParse.cpp
- test/db/extras/r2ghidra
This PR implements an annotator for annotating local variables and function parameters. The annotator uses the color attribute in the XML for classifying variables as local variables and function parameters. 
...
**Test plan**
1. Fetch [PR #17375](https://github.com/radareorg/radare2/pull/17375)  from radare2 and compile it.
2. Load any function (test functions with local variables and functions without local variables).
3. Pipe the output of `pdgj~{}` to a file and open it in an editor of your choice.
4. Because of the order of annotations, syntax highlight annotator with come right after local variable anntoation.
5. Search for `"syntax_highlight": "function_parameter"` and `"syntax_highlight": "local_variable"`. Make sure that you are seeing the exact local …
> Annotator for local variables and function paramters

- scripts/Dockerfile.jessie
- src/CodeXMLParse.cpp
- test/db/extras/r2ghidra
As part of the [Improving Decompiler Widget](https://github.com/orgs/radareorg/projects/1) project, many new types of annotations have been added. This was merged to radare2 by [PR #17429](https://github.com/radareorg/radare2/pull/17429).
The annotators for these new annotations were implemented and merged to the `decompiler-refactoring` branch by the following PRs:
1. #123 - Function name annotation annotator implemented.
2. #124 - Annotator for constant and global variables.
3. #128 - Annotator for local variables and function parameters.
...
**Test plan**
1. Fetch the master of radare2 and compile.
2. Compile this PR.
3. Run tests in `r2ghidra-dec` and make sure the new tests are passing. New tests added tests all the annotators that were implemented by the …
> Annotators for new annotations

- cmake/FindRadare2.cmake
The recent SDB header PR [#17249](https://github.com/radareorg/radare2/pull/17249/) requires us to add the sdb header's path separately from the other r2 headers. This broke Cutter's r2ghidra-dec windows build as you can see in this job https://ci.appveyor.com/project/radareorg/cutter/builds/34583435/job/98wog65qjgx9t4sf#L3091
**Test plan**
Build in Windows using msys.
> Fix windows build

- cutter-plugin/R2GhidraDecompiler.cpp
- cutter-plugin/R2GhidraDecompiler.h
Implementing decompiler `isRunning()` was missed out while refactoring the decompiler interface in r2ghidra-dec. This PR fixes it.
...
**Test plan**
1. Check code.
2. Due to some regression as pointed out by @karliss [in this discussion,](https://github.com/radareorg/cutter/pull/2402#discussion_r475795188) this can't be tested right now. You can modify the code to maybe set `task = DecompilerRunning` to make sure the decompiler interface in Cutter able to get the required data from the r2ghidra-dec.
...
...
> Implement decompiler isRunning() 

- CMakeLists.txt
- src/SleighAsm.cpp
- src/SleighAsm.h
- src/SleighInstruction.cpp
- src/SleighInstruction.h
- src/anal_ghidra.cpp
- src/asm_ghidra.cpp
- src/core_ghidra.cpp
- test/db/extras/anal_ghidra
- test/db/extras/asm_ghidra
- test/db/extras/r2ghidra
* Improve `pdgsd` result in RCore plugin.
* Port `SleighInstructionPrototype` from Ghidra's JAVA codebase to identify instruction's control flow type from underlying `Constructor`.
* Implement as-much-as-possible P-code to ESIL translation.
* Implement pattern-match on P-codes to identify type of single instruction.
* Improve processor and compiler spec file parse to extract reg info.
* Add `pdga` command to RCore plugin to enable this plugin.
* Enable plugin's compilation option as default.
**Test plan**
Has been tested on 8 cases in r2-testbins. Test cases will be added in next pr.
> RAnal SLEIGH plugin

- CMakeLists.txt
- cmake/FindCutter.cmake
- cutter-plugin/CMakeLists.txt
Various changes to help with building Cutter plugin as dll on windows instead of current approach of static linking and relying on delayed symbol lookup at runtime.
* Change RADARE2_INSTALL_PLUGDIR and CUTTER_INSTALL_PLUGDIR as STRING instead of PATH so that you use paths relative to CMAKE_INSTALL_PREFIX. The cmake install commands where those variables are used handle relative paths relative to install prefix. But setting the variables as PATH causes them to be resolved relative to current directory at least on windows thus preventing them to be used that way.  Use of absolute paths is still supported.
* When available use CutterConfig.cmake from Cutter installation instead of custom code in FindCutter.  In future it will be possible to remove FindCutter.cmake …
> Adjust CMake for building Cutter plugin for windows as dll.

- src/R2Scope.cpp
r_anal_fc_label_at has been deprecated
```c
src/r2ghidra-dec/src/R2Scope.cpp:500:22: error: 'r_anal_fcn_label_at' was not declared in this scope
```
**Test plan**
make
build
> Fix build for r2 >= 4.6

- CMakeLists.txt
build of asm and anal plugins in mac use a linux-specific linker flag which makes it unloadable.
```
R2_DEBUG=1 r2 -
PLUGIN LOADED 0x7fb55d93f7f0 fcn 0x109167260
Loading /Users/pancake/.local/share/radare2/plugins/asm_ghidra.dylib
r_lib_dl_open: error: /Users/pancake/.local/share/radare2/plugins/asm_ghidra.dylib (dlopen(/Users/pancake/.local/share/radare2/plugins/asm_ghidra.dylib, 9): Library not loaded: @rpath/core_ghidra.dylib
Referenced from: /Users/pancake/.local/share/radare2/plugins/asm_ghidra.dylib
Reason: image not found)
Cannot open library: '/Users/pancake/.local/share/radare2/plugins/asm_ghidra.dylib'
Loading /Users/pancake/.local/share/radare2/plugins/anal_ghidra.dylib
r_lib_dl_open: error: /Users/pancake/.local/share/radare2/plugins/anal_ghidra.dylib …
```
> Fix RPATH issue in the asm/anal plugins for macOS

- src/anal_ghidra.cpp
Fixes some of the crashes reported in #150 
will submit more fixes when this gets merged
> Wrap all the Sleight.init calls in try/catch to avoid segfault if invalid id provided

- src/anal_ghidra.cpp
Segfaults
**Test plan**
```
$ r2 -a r2ghidra -b 32 -e asm.cpu=v850 -s 0xc8d0 -c 'wx 8007 d0c8;ao' -
WARNING: No calling convention defined for this file, analysis may be inaccurate.
zsh: segmentation fault  r2 -a r2ghidra -b 32 -e asm.cpu=v850 -s 0xc8d0 -c 'wx 8007 d0c8;ao' -
$
```
none registered
> Fix null derefs after r_reg_get

- src/anal_ghidra.cpp
- test/db/extras/anal_ghidra
When analyzing some v850 instructions, the op.type is not filled properly i would say CMP and LOAD, STORE ops are the main problematic ones from what i see.
Theres probably a better fix for this, but i would love to hear from the experts in here to get a better/more generic fix, also i think this optype deduction out of the sleigh expression should have more tests. but im impressed by how well it works out of the box after sorting out all the segfaults already fixed.
Awesome work!
**Test plan**
added a couple of tests
not sure if i spent the time to fill an issue for this
> Fill op->type for CMP instructions

- .github/workflows/codeql-analysis.yml
One of the steps is not needed anymore and it shows a warning for that.
> CI: fix CodeQL warning

- test/db/extras/ghidra
Show noreturn attribute  for no return function
now the expected output like this:
```c
void sym.imp.exit noreturn (void)
{
// WARNING: Treating indirect jump as call
(*_reloc.dyld_stub_binder)();
returndebug in rz_core_annotated_code_print;
}
```
**Test plan:**
seek to a noreturn function and `pdg` to see.
**Closing issue:**
closes #86 
**Testbin**
[rr.zip](https://github.com/radareorg/r2ghidra-dec/files/3670319/rr.zip)
> Add noreturn show in function signature

- .travis.yml
> Add ARMv8, PPC64, SystemZ Travis
